language: node_js
node_js:
- 8
branches:
  only:
  - master
  - development
before_script:
- npm install
script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then ng build --prod --aot=false; fi
- if [ "$TRAVIS_BRANCH" = "development" ]; then ng build; fi
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
