language: node_js
node_js:
- 8
branches:
  only:
  - master
  - development
before_script:
- npm install
script:
- ng build --prod --aot=false
  if: branch = master
script:
- ng build
  if: branch = development
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
