language: node_js
node_js:
- 8
branches:
  only:
  - master
before_script:
- npm install
script:
- ng build --prod --aot=false
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
