language: node_js
node_js:
- 8
before_script:
- npm install
script:
- ng build --prod
deploy:
  provider: firebase
  token:
    secure: "jZTJfqffx6gCAZik4h4Xw+6Aw4+2KU5y+4lXqrdxLJmiGb2V8EcsuJKUDQGGG46fYAqwo/oLHbadYlwLJV86LDHKxQtfYzRxZW0GfKwwZGrc6tmLdJSI2v2T+Z6EN/09p6YBozZ5WHGV0A9D7AaVIx50zrkwrIS3wx7sFvbaP1fJojMeFK9hep1YAt9Gt2GiEgjZE/pE7rrrHFwsMfNMHCWiujOPYfMQYrYs0ZXpuplJeox0HUWe/fdCfNVkgfKDH8zOYau7FEZ0UEv7WeTRPlVBRiO+tQS9546t6cwSVca8ZdD/ZuB014bRdL8JR54Nbg6rvvrgJq9EZxrCBACEjd5CG6eyo988AX1OdqBu2QFoT2t9It9wQwQFAUzo/2W6mjhTIyRgIVROPqahb4qBV7RALH0JM0oThDD5gQ6aEdRiE9C3rzNoHghfjxOejKBIsdEBRCEMDdp4dAAhy1dCtZo68aV0k0bD0ys28ThUHjco77WUKXqX3BAA0IElkgl6wi0ckJac8U6bXTynlIvicUt7Hbn0XC6O+EWgy7Avg165R2AUmd31cIxn7WF/bEKR1pEO6bUQn3v48Ee/aMpgNnCl5cCwAgwP3VXoqHBZXYc285RhmM5zqvoORWe/sqHOt6oEb9m/aQMlCxbQwDkrBAPfE0Iw1qMvHpq5PovtlAk="
  project: "mue-shoplist"