language: node_js
node_js:
- 8
before_script:
- npm install
script:
- ng build --prod
deploy:
  provider: firebase
  token:
    secure: kNVdoT4Zenns9ptWtd7nbxZzuobcDCkn3HLkIr4CmlLf0IISYtBAvCHfiWAh/kwmD/frqCTWklZgCG9Dkc6+z6PgQap2E+E2iTr3LyR7vk6jrRurmQBBBkWerhyxUrvlApQkV80vtf7+wWrs73yq/JwPqCAmxrnW7HBOsfYeNPPWtADttgsrcClwF4wbgYXiL7zGhiH2TWbdozh1fBr/qUgwJjQjpxPtZhqzAjoXp9rsEV+ZZuD70lUH6GTM1SOiwMvc16uURKznCVQRwZn9Lcz2dSYhnbViW0eBypjd4N71JljhsCYGwTsOWAgXufgfUOvzxJ+0SUfjqBX0UScnJPrnBywBZECJNExuUNY27RHBVej84ZhqozAnGYE4zy302Xk81tmJ1HtcKwbyHtLcIrrp+1lkrIXeyXNqphdOritOQ3QfLuqglh9CV6oCsJz3hyiKNkKdc+UCFn4uzBDjECyAo3NKsaXZZTnuLHbePC3h7riHSC6aSHq6hpy8neeSuvULPHMxSV2Ub07CAy1BVIFO+zcVIcrxVF7ymAkrmeV3FEIO3k50B0h+angJ/b03s8xcxmmfanlFr84UJmab7KS1I4EDQFIevzwJjjqw7P50G9dQLlOCKm3xID8WVy0w9S78gXiHRyqH0tRnaYj0AUoM+Cof9l9RALmwTFOhteo=
env:
  global:
    secure: kNVdoT4Zenns9ptWtd7nbxZzuobcDCkn3HLkIr4CmlLf0IISYtBAvCHfiWAh/kwmD/frqCTWklZgCG9Dkc6+z6PgQap2E+E2iTr3LyR7vk6jrRurmQBBBkWerhyxUrvlApQkV80vtf7+wWrs73yq/JwPqCAmxrnW7HBOsfYeNPPWtADttgsrcClwF4wbgYXiL7zGhiH2TWbdozh1fBr/qUgwJjQjpxPtZhqzAjoXp9rsEV+ZZuD70lUH6GTM1SOiwMvc16uURKznCVQRwZn9Lcz2dSYhnbViW0eBypjd4N71JljhsCYGwTsOWAgXufgfUOvzxJ+0SUfjqBX0UScnJPrnBywBZECJNExuUNY27RHBVej84ZhqozAnGYE4zy302Xk81tmJ1HtcKwbyHtLcIrrp+1lkrIXeyXNqphdOritOQ3QfLuqglh9CV6oCsJz3hyiKNkKdc+UCFn4uzBDjECyAo3NKsaXZZTnuLHbePC3h7riHSC6aSHq6hpy8neeSuvULPHMxSV2Ub07CAy1BVIFO+zcVIcrxVF7ymAkrmeV3FEIO3k50B0h+angJ/b03s8xcxmmfanlFr84UJmab7KS1I4EDQFIevzwJjjqw7P50G9dQLlOCKm3xID8WVy0w9S78gXiHRyqH0tRnaYj0AUoM+Cof9l9RALmwTFOhteo=
